title: Xi Cen Homepage
page-top-title: Xi Cen Homepage
top-section-bg-text: A Dedicated NLP & ML System Nerd Dreaming of AGI World
home-subtitle: Xi Cen
copyright-text: '&copy; Xi Cen 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'

